config/routes.rb
RailsStripeMembershipSaas::Application.routes.draw do
  resources :addresses
  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'static_pages#home'
  end
  root :to => "static_pages#home"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users

    match '/about',  to: 'static_pages#about',         via: 'get'
    match '/faqs',  to: 'static_pages#faqs',         via: 'get'
    match '/termsandconditions',  to: 'static_pages#terms',         via: 'get'
    match '/privacypolicy',  to: 'static_pages#privacy',         via: 'get'



end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Clockwork Flies", root_path, :class => 'brand' %>
<ul class="nav pull-right">
  <% if user_signed_in?
    then %>
   
    <% else %>

  <li>
    <%= link_to "Buy", root_path(anchor: "buy"), "data-toggle" => "elementscroll" %>
  </li>
  <li>
    <%= link_to "What you get", root_path(anchor: "whatyouget"), "data-toggle" => "elementscroll" %>
  </li>
  <li>
    <%= link_to "How it works", root_path(anchor: "howitworks"), "data-toggle" => "elementscroll" %>
  </li>
  <li>
    <%= link_to "Customer quotes", root_path(anchor: "socialproof"), "data-toggle" => "elementscroll" %>
  </li>
  <li>
    <%= link_to 'About us', root_path(anchor: "about"), "data-toggle" => "elementscroll" %>
  </li>
  <!--
  <li>
    <%= link_to 'FAQs', root_path(anchor: "faqs"), "data-toggle" => "elementscroll" %>
  </li>
-->

    <% end %>
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li >
      <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
        <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Clockwork Flies" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Clockwork Flies" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <!-- GA code -->
    <% if Rails.env.production? %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        
        ga('create', 'UA-47821133-1', 'clockworkflies.com');
        ga('send', 'pageview');
      </script>
    <% end %>
    <!-- GA code end -->
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container-fluid">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div>
        <div class="content">
          <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <div class="footer">
              <div class="container-fluid">
                <div class="pull-left">
                  © Clockwork Flies 2014|
                  <%= link_to 'About', about_path, :class => 'white' %>
                  |
                  <%= link_to 'Terms & Conditions', termsandconditions_path, :class => 'white' %>
                </div>
                <div class="pull-right">
                  Catch more.
                </div>
              </div>
            </div>
          </footer>
        </div>
      </div>
      <!--! end of .container -->
    </div>
    <!--! end of #main -->
  </body>
</html>